datasets_path: 'C:\Datasets'
random_seed: 230

stft_format: realimag # realimag or magphase

Model:
  model_name: SpeechDAREUnet_v1
  learning_rate: 0.001

DataLoader:
  batch_size: 4
  shuffle: True
  drop_last: True
  num_workers: 8
  pin_memory: True
  persistent_workers: True

ModelCheckpoint:
  monitor: val_loss
  dirpath: 'C:\SpeechDARE\checkpoints'

DDPStrategy:
  process_group_backend: gloo
  find_unused_parameters: False

Trainer:
  limit_train_batches: 10
  limit_val_batches: 2
  limit_test_batches: 2
  max_epochs: 10
  log_every_n_steps: 10
  accelerator: gpu
  devices: 1
  profiler: null

RichProgressBarTheme:
  description: green_yellow
  progress_bar: green1
  progress_bar_finished: green1
  progress_bar_pulse: '#6206E0'
  batch_progress: green_yellow
  time: grey82
  processing_speed: grey82
  metrics: grey82
