datasets_path: 'C:\Datasets'
random_seed: 230

data_in_ram: False

stft_format: realimag # realimag or magphase
rir_duration: 32767
nfft: 16383
nhop: 2048
nfrms: 16

Model:
  model_name: SpeechDAREUnet_v2
  learning_rate: 0.0001
  nfft: 8192
  nfrms: 16
  use_transformer: True

DataLoader:
  batch_size: 128
  num_workers: 16
  persistent_workers: True
  shuffle: True
  drop_last: True
  pin_memory: True

ModelCheckpoint:
  monitor: val_loss
  dirpath: checkpoints

LearningRateMonitor:
  logging_interval: epoch

DataParallelStrategy:
  # process_group_backend: gloo
  # find_unused_parameters: False
  accelerator: gpu

AdvancedProfiler:
  dirpath: null
  filename: advanced_profiler.txt
  line_count_restriction: 1.0

Trainer:
  limit_train_batches: 2220
  limit_val_batches: 3
  limit_test_batches: 111
  max_epochs: 100
  # reload_dataloaders_every_n_epochs: 1
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
  log_every_n_steps: 100
  check_val_every_n_epoch: 5
  # accelerator: gpu
  devices: 3

RichProgressBar:
  refresh_rate: 1
  leave: True

RichProgressBarTheme:
  description: green_yellow
  progress_bar: green1
  progress_bar_finished: green1
  progress_bar_pulse: '#6206E0'
  batch_progress: green_yellow
  time: grey82
  processing_speed: grey82
  metrics: grey82
